spring:
 datasource:
  url: jdbc:mysql://localhost:3306/zljjc?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&allowPublicKeyRetrieval=true
  username: root
  password: yj123!@#
  driver-class-name: com.mysql.jdbc.Driver
 
mybatis: 
  mapper-locations: classpath*:mapper/*.xml
  config-location: classpath:mybatis-config.xml